language: php

php:
  - 7.2
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --no-dev
  - cp phpunit.xml.dist phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
